version: "3"

services:
  nest-notebook:
    container_name: nest-simulation
    image: nest/nest-simulator:3.4
    volumes:
      - .:/opt/data
    environment:
      LOCAL_USER_ID: "`id -u $USER`"
      NEST_CONTAINER_MODE: "notebook"

